version: 2.1

executors:
  cpp:
    docker:
      - image: gcc:latest

jobs:
  run_emojicode:
    executor: cpp
    steps:
      - checkout
      - run:
          name: install rsync
          command: |
            apt install -y sudo && \
            sudo apt install -y rsync
      - run:
          name: install emojicode
          command: |
            wget https://github.com/emojicode/emojicode/releases/download/v1.0-beta.2/Emojicode-1.0-beta.2-Linux-x86_64.tar.gz -O emojicode.tar.gz \
            && tar -xzf emojicode.tar.gz && rm emojicode.tar.gz \
            && cd Emojicode-1.0-beta.2-Linux-x86_64 && yes | sudo ./install.sh \
            && cd .. && rm -r Emojicode-1.0-beta.2-Linux-x86_64
      - run:
          name: build emojicode
          command: emojicodec hello.emojic
      - run:
          name: run
          command: ./hello

workflows:
  version: 2
  build:
    jobs: 
      - run_emojicode
