version: 2.1

ubuntu_image: &ubuntu_image
  ubuntu:18.04

orbs:
  emojicode: yutagoto/emojicode@1.0.0

executors:
  ubuntu-docker:
    docker:
      - image: *ubuntu_image
        environment:
          TZ: Asia/Tokyo

jobs:
  run_emojicode:
    executor: ubuntu-docker
    steps:
      - checkout
      - run: apt update && apt install -y sudo wget || true
      - emojicode/install
      - run:
          name: build emojicode
          command: emojicodec hello.emojic
      - run:
          name: run
          command: ./hello

workflows:
  version: 2
  build:
    jobs:
      - run_emojicode
