version: 2.1

orbs:
  emojicode: yutagoto/emojicode@1.0.0

executors:
  cpp:
    docker:
      - image: gcc:latest

jobs:
  run_emojicode:
    executor: cpp
    steps:
      - checkout
      - run: apt update && apt install -y sudo || true
      - emojicode/install
      - run:
          name: build emojicode
          command: emojicodec hello.emojic
      - run:
          name: run
          command: ./hello

workflows:
  version: 2
  build:
    jobs:
      - run_emojicode
